name: Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verify Heroku CLI
        run: heroku version
      - name: Log in to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dontuseforce: 1
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
      - name: Deploy to Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
