name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        uses: actions/heroku@v1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app: ${{ secrets.HEROKU_APP_NAME }}

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t registry.heroku.com/my-fastapi-app/web .
          docker login -u _ -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          docker push registry.heroku.com/my-fastapi-app/web

      - name: Release to Heroku
        uses: actions/heroku@v1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app: ${{ secrets.HEROKU_APP_NAME }}
          command: 'docker-compose up -d'
